import BuildBattle, { BuildBattleWins } from './BuildBattle';
import { expect, expectTypeOf, test } from 'vitest';

test('BuildBattle', () => {
  const data = new BuildBattle({ stats: 'meow' });
  expect(data).toBeInstanceOf(BuildBattle);
  expectTypeOf(data).toEqualTypeOf<BuildBattle>();
  expect(data.score).toBeDefined();
  expect(data.score).greaterThanOrEqual(0);
  expectTypeOf(data.score).toEqualTypeOf<number>();
  expect(data.totalWins).toBeDefined();
  expect(data.totalWins).greaterThanOrEqual(0);
  expectTypeOf(data.totalWins).toEqualTypeOf<number>();
  expect(data.games).toBeDefined();
  expect(data.games).greaterThanOrEqual(0);
  expectTypeOf(data.games).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).greaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
  expect(data.superVotes).toBeDefined();
  expect(data.superVotes).greaterThanOrEqual(0);
  expectTypeOf(data.superVotes).toEqualTypeOf<number>();
  expect(data.coins).toBeDefined();
  expect(data.coins).greaterThanOrEqual(0);
  expectTypeOf(data.coins).toEqualTypeOf<number>();
  expect(data.totalVotes).toBeDefined();
  expect(data.totalVotes).greaterThanOrEqual(0);
  expectTypeOf(data.totalVotes).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expectTypeOf(data.wins).toEqualTypeOf<BuildBattleWins>();
  expect(data.wins.solo).toBeDefined();
  expect(data.wins.solo).greaterThanOrEqual(0);
  expectTypeOf(data.wins.solo).toEqualTypeOf<number>();
  expect(data.wins.teams).toBeDefined();
  expect(data.wins.teams).greaterThanOrEqual(0);
  expectTypeOf(data.wins.teams).toEqualTypeOf<number>();
  expect(data.wins.pro).toBeDefined();
  expect(data.wins.pro).greaterThanOrEqual(0);
  expectTypeOf(data.wins.pro).toEqualTypeOf<number>();
  expect(data.wins.gtb).toBeDefined();
  expect(data.wins.gtb).greaterThanOrEqual(0);
  expectTypeOf(data.wins.gtb).toEqualTypeOf<number>();
});
