import ChocolateFactory from './ChocolateFactory';
import CrimsonIsle from './CrimsonIsle';
import Dungeons from './Dungeons';
import HOTM from './HOTM';
import Jacob from './Jacob';
import Minions from './Minion';
import Skills from './Skills';
import SkyblockGarden from '../SkyblockGarden';
import SkyblockMember from './Member';
import SkyblockMuseum from '../SkyblockMuseum';
import SkyblockPet from '../SkyblockPet';
import Slayers from './Slayers';
import Stats from './Stats';
import { expect, expectTypeOf, test } from 'vitest';

test('SkyblockMember', () => {
  const data = new SkyblockMember({ stats: 'meow' });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(SkyblockMember);
  expectTypeOf(data).toEqualTypeOf<SkyblockMember>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.gameMode).toBeDefined();
  expectTypeOf(data.gameMode).toEqualTypeOf<string | null>();
  expect(data.selected).toBeDefined();
  expectTypeOf(data.selected).toEqualTypeOf<boolean>();
  expect(data.garden).toBeDefined();
  expectTypeOf(data.garden).toEqualTypeOf<SkyblockGarden | null>();
  expect(data.museum).toBeDefined();
  expectTypeOf(data.museum).toEqualTypeOf<SkyblockMuseum | null>();
  expect(data.profileName).toBeDefined();
  expectTypeOf(data.profileName).toEqualTypeOf<string>();
  expect(data.profileId).toBeDefined();
  expectTypeOf(data.profileId).toEqualTypeOf<string>();
  expect(data.firstJoinTimestamp).toBeDefined();
  expectTypeOf(data.firstJoinTimestamp).toEqualTypeOf<number | null>();
  expect(data.firstJoinAt).toBeDefined();
  expectTypeOf(data.firstJoinAt).toEqualTypeOf<Date | null>();
  expect(data.experience).toBeDefined();
  expect(data.experience).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.experience).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expect(data.level).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.level).toEqualTypeOf<number>();
  expect(data.hotm).toBeDefined();
  expect(data.hotm).toBeInstanceOf(HOTM);
  expectTypeOf(data.hotm).toEqualTypeOf<HOTM>();
  expect(data.highestMagicalPower).toBeDefined();
  expect(data.highestMagicalPower).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.highestMagicalPower).toEqualTypeOf<number>();
  expect(data.fairySouls).toBeDefined();
  expect(data.fairySouls).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fairySouls).toEqualTypeOf<number>();
  expect(data.fairyExchanges).toBeDefined();
  expect(data.fairyExchanges).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.fairyExchanges).toEqualTypeOf<number>();
  expect(data.skills).toBeDefined();
  expect(data.skills).toBeInstanceOf(Skills);
  expectTypeOf(data.skills).toEqualTypeOf<Skills>();
  expect(data.bestiary).toBeDefined();
  expect(data.bestiary).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bestiary).toEqualTypeOf<number>();
  expect(data.slayer).toBeDefined();
  expect(data.slayer).toBeInstanceOf(Slayers);
  expectTypeOf(data.slayer).toEqualTypeOf<Slayers>();
  expect(data.crimsonIsle).toBeDefined();
  expect(data.crimsonIsle).toBeInstanceOf(CrimsonIsle);
  expectTypeOf(data.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
  expect(data.dungeons).toBeDefined();
  expect(data.dungeons).toBeInstanceOf(Dungeons);
  expectTypeOf(data.dungeons).toEqualTypeOf<Dungeons>();
  expect(data.collections).toBeDefined();
  expectTypeOf(data.collections).toEqualTypeOf<Record<string, number>>();
  expect(data.purse).toBeDefined();
  expect(data.purse).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.purse).toEqualTypeOf<number>();
  expect(data.stats).toBeDefined();
  expect(data.stats).toBeInstanceOf(Stats);
  expectTypeOf(data.stats).toEqualTypeOf<Stats>();
  expect(data.pets).toBeDefined();
  expectTypeOf(data.pets).toEqualTypeOf<SkyblockPet[]>();
  expect(data.jacob).toBeDefined();
  expect(data.jacob).toBeInstanceOf(Jacob);
  expectTypeOf(data.jacob).toEqualTypeOf<Jacob>();
  expect(data.chocolate).toBeDefined();
  expect(data.chocolate).toBeInstanceOf(ChocolateFactory);
  expectTypeOf(data.chocolate).toEqualTypeOf<ChocolateFactory>();
  expect(data.minions).toBeDefined();
  expect(data.minions).toBeInstanceOf(Minions);
  expectTypeOf(data.minions).toEqualTypeOf<Minions>();
});
