import ChocolateFactory from '../structures/SkyBlock/Member/ChocolateFactory';
import Client from '../Client';
import CrimsonIsle from '../structures/SkyBlock/Member/CrimsonIsle';
import Dungeons from '../structures/SkyBlock/Member/Dungeons';
import HOTM from '../structures/SkyBlock/Member/HOTM';
import Jacob from '../structures/SkyBlock/Member/Jacob';
import Minions from '../structures/SkyBlock/Member/Minion';
import Skills from '../structures/SkyBlock/Member/Skills';
import SkyblockGarden from '../structures/SkyBlock/SkyblockGarden';
import SkyblockInventoryItem, { SkyblockGemstone } from '../structures/SkyBlock/SkyblockInventoryItem';
import SkyblockMember from '../structures/SkyBlock/Member/Member';
import SkyblockMuseum from '../structures/SkyBlock/SkyblockMuseum';
import SkyblockPet from '../structures/SkyBlock/SkyblockPet';
import Slayers from '../structures/SkyBlock/Member/Slayers';
import Stats from '../structures/SkyBlock/Member/Stats';
import { Armor, Equipment, Rarity } from '../structures/SkyBlock/Member/Types';
import { NetworthResult } from 'skyhelper-networth';
import { expect, expectTypeOf, test } from 'vitest';

test('getSkyblockMember (raw)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  const data = await client.getSkyblockMember('14727faefbdc4aff848cd2713eb9939e', { raw: true });
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<object>();
  client.destroy();
});

test('getSkyblockMember (no input)', () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  expect(() => client.getSkyblockMember()).rejects.toThrowError(client.errors.NO_NICKNAME_UUID);
  client.destroy();
});

test('getSkyblockMember (no profiles)', () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  expect(() => client.getSkyblockMember('b45add7b081443909fb00aa9a3e15eb0')).rejects.toThrowError(
    client.errors.NO_SKYBLOCK_PROFILES
  );
  client.destroy();
});

test('getSkyblockMember (museum)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  const data = await client.getSkyblockMember('add71246c46e455c8345c129ea6f146c', { museum: true });
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<SkyblockMember[]>();
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expect(member.garden).toBeNull();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expect(member.level).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expect(member.hotm).toBeInstanceOf(HOTM);
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expect(member.highestMagicalPower).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expect(member.fairySouls).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expect(member.fairyExchanges).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expect(member.skills).toBeInstanceOf(Skills);
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expect(member.bestiary).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expect(member.slayer).toBeInstanceOf(Slayers);
    expectTypeOf(member.slayer).toEqualTypeOf<Slayers>();
    expect(member.crimsonIsle).toBeDefined();
    expect(member.crimsonIsle).toBeInstanceOf(CrimsonIsle);
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expect(member.dungeons).toBeInstanceOf(Dungeons);
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expect(member.purse).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expect(member.stats).toBeInstanceOf(Stats);
    expectTypeOf(member.stats).toEqualTypeOf<Stats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
    });
    expect(member.jacob).toBeDefined();
    expect(member.jacob).toBeInstanceOf(Jacob);
    expectTypeOf(member.jacob).toEqualTypeOf<Jacob>();
    expect(member.chocolate).toBeDefined();
    expect(member.chocolate).toBeInstanceOf(ChocolateFactory);
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactory>();
    expect(member.minions).toBeDefined();
    expect(member.minions).toBeInstanceOf(Minions);
    expectTypeOf(member.minions).toEqualTypeOf<Minions>();
    expect(member.getArmor).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    const armor = await member.getArmor();
    expect(armor).toBeDefined();
    expectTypeOf(armor).toEqualTypeOf<Armor>();
    expect(armor.helmet).toBeDefined();
    expectTypeOf(armor.helmet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.chestplate).toBeDefined();
    expectTypeOf(armor.chestplate).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.leggings).toBeDefined();
    expectTypeOf(armor.leggings).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.boots).toBeDefined();
    expectTypeOf(armor.boots).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getWardrobe).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const wardrobe = await member.getWardrobe();
    expect(wardrobe).toBeDefined();
    expectTypeOf(wardrobe).toEqualTypeOf<SkyblockInventoryItem[]>();
    wardrobe.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getEnderChest).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const enderChest = await member.getEnderChest();
    expect(enderChest).toBeDefined();
    expectTypeOf(enderChest).toEqualTypeOf<SkyblockInventoryItem[]>();
    enderChest.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getInventory).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const inventory = await member.getInventory();
    expect(inventory).toBeDefined();
    expectTypeOf(inventory).toEqualTypeOf<SkyblockInventoryItem[]>();
    inventory.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getPetScore).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    const petScore = member.getPetScore();
    expect(petScore).toBeDefined();
    expect(member.getEquipment).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    const equipment = await member.getEquipment();
    expect(equipment).toBeDefined();
    expectTypeOf(equipment).toEqualTypeOf<Equipment>();
    expect(equipment.gauntlet).toBeDefined();
    expectTypeOf(equipment.gauntlet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.belt).toBeDefined();
    expectTypeOf(equipment.belt).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.cloak).toBeDefined();
    expectTypeOf(equipment.cloak).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.necklace).toBeDefined();
    expectTypeOf(equipment.necklace).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getPersonalVault).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const vault = await member.getPersonalVault();
    expect(vault).toBeDefined();
    expectTypeOf(vault).toEqualTypeOf<SkyblockInventoryItem[]>();
    vault.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getNetworth).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    const networth = await member.getNetworth();
    expect(networth).toBeDefined();
    expectTypeOf(networth).toEqualTypeOf<NetworthResult | null>();
    expect(member.getFarmingWeight).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    const farmingWeight = member.getFarmingWeight();
    expect(farmingWeight).toBeDefined();
    expect(farmingWeight).toBeGreaterThanOrEqual(0);
    expectTypeOf(farmingWeight).toEqualTypeOf<number>();
  });
  client.destroy();
});

test('getSkyblockMember (garden)', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  const data = await client.getSkyblockMember('add71246c46e455c8345c129ea6f146c', { garden: true });
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<SkyblockMember[]>();
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expect(member.museum).toBeNull();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expect(member.level).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expect(member.hotm).toBeInstanceOf(HOTM);
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expect(member.highestMagicalPower).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expect(member.fairySouls).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expect(member.fairyExchanges).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expect(member.skills).toBeInstanceOf(Skills);
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expect(member.bestiary).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expect(member.slayer).toBeInstanceOf(Slayers);
    expectTypeOf(member.slayer).toEqualTypeOf<Slayers>();
    expect(member.crimsonIsle).toBeDefined();
    expect(member.crimsonIsle).toBeInstanceOf(CrimsonIsle);
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expect(member.dungeons).toBeInstanceOf(Dungeons);
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expect(member.purse).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expect(member.stats).toBeInstanceOf(Stats);
    expectTypeOf(member.stats).toEqualTypeOf<Stats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
    });
    expect(member.jacob).toBeDefined();
    expect(member.jacob).toBeInstanceOf(Jacob);
    expectTypeOf(member.jacob).toEqualTypeOf<Jacob>();
    expect(member.chocolate).toBeDefined();
    expect(member.chocolate).toBeInstanceOf(ChocolateFactory);
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactory>();
    expect(member.minions).toBeDefined();
    expect(member.minions).toBeInstanceOf(Minions);
    expectTypeOf(member.minions).toEqualTypeOf<Minions>();
    expect(member.getArmor).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    const armor = await member.getArmor();
    expect(armor).toBeDefined();
    expectTypeOf(armor).toEqualTypeOf<Armor>();
    expect(armor.helmet).toBeDefined();
    expectTypeOf(armor.helmet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.chestplate).toBeDefined();
    expectTypeOf(armor.chestplate).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.leggings).toBeDefined();
    expectTypeOf(armor.leggings).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.boots).toBeDefined();
    expectTypeOf(armor.boots).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getWardrobe).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const wardrobe = await member.getWardrobe();
    expect(wardrobe).toBeDefined();
    expectTypeOf(wardrobe).toEqualTypeOf<SkyblockInventoryItem[]>();
    wardrobe.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getEnderChest).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const enderChest = await member.getEnderChest();
    expect(enderChest).toBeDefined();
    expectTypeOf(enderChest).toEqualTypeOf<SkyblockInventoryItem[]>();
    enderChest.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getInventory).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const inventory = await member.getInventory();
    expect(inventory).toBeDefined();
    expectTypeOf(inventory).toEqualTypeOf<SkyblockInventoryItem[]>();
    inventory.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getPetScore).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    const petScore = member.getPetScore();
    expect(petScore).toBeDefined();
    expect(member.getEquipment).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    const equipment = await member.getEquipment();
    expect(equipment).toBeDefined();
    expectTypeOf(equipment).toEqualTypeOf<Equipment>();
    expect(equipment).toBeDefined();
    expectTypeOf(equipment).toEqualTypeOf<Equipment>();
    expect(equipment.gauntlet).toBeDefined();
    expectTypeOf(equipment.gauntlet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.belt).toBeDefined();
    expectTypeOf(equipment.belt).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.cloak).toBeDefined();
    expectTypeOf(equipment.cloak).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.necklace).toBeDefined();
    expectTypeOf(equipment.necklace).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getPersonalVault).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const vault = await member.getPersonalVault();
    expect(vault).toBeDefined();
    expectTypeOf(vault).toEqualTypeOf<SkyblockInventoryItem[]>();
    vault.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getNetworth).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    const networth = await member.getNetworth();
    expect(networth).toBeDefined();
    expectTypeOf(networth).toEqualTypeOf<NetworthResult | null>();
    expect(member.getFarmingWeight).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    const farmingWeight = member.getFarmingWeight();
    expect(farmingWeight).toBeDefined();
    expect(farmingWeight).toBeGreaterThanOrEqual(0);
    expectTypeOf(farmingWeight).toEqualTypeOf<number>();
  });
  client.destroy();
});

test('getSkyblockMember', async () => {
  const client = new Client(process.env.HYPIXEL_KEY ?? '', { cache: false, checkForUpdates: false, rateLimit: 'NONE' });
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  const data = await client.getSkyblockMember('14727faefbdc4aff848cd2713eb9939e');
  expect(data).toBeDefined();
  expectTypeOf(data).toEqualTypeOf<SkyblockMember[]>();
  data.forEach(async (member: SkyblockMember) => {
    expect(member).toBeDefined();
    expect(member).toBeInstanceOf(SkyblockMember);
    expectTypeOf(member).toEqualTypeOf<SkyblockMember>();
    expect(member.uuid).toBeDefined();
    expectTypeOf(member.uuid).toEqualTypeOf<string>();
    expect(member.gameMode).toBeDefined();
    expectTypeOf(member.gameMode).toEqualTypeOf<string | null>();
    expect(member.selected).toBeDefined();
    expectTypeOf(member.selected).toEqualTypeOf<boolean>();
    expect(member.garden).toBeDefined();
    expect(member.garden).toBeNull();
    expectTypeOf(member.garden).toEqualTypeOf<SkyblockGarden | null>();
    expect(member.museum).toBeDefined();
    expect(member.museum).toBeNull();
    expectTypeOf(member.museum).toEqualTypeOf<SkyblockMuseum | null>();
    expect(member.profileName).toBeDefined();
    expectTypeOf(member.profileName).toEqualTypeOf<string>();
    expect(member.profileId).toBeDefined();
    expectTypeOf(member.profileId).toEqualTypeOf<string>();
    expect(member.firstJoinTimestamp).toBeDefined();
    expectTypeOf(member.firstJoinTimestamp).toEqualTypeOf<number | null>();
    expect(member.firstJoinAt).toBeDefined();
    expectTypeOf(member.firstJoinAt).toEqualTypeOf<Date | null>();
    expect(member.experience).toBeDefined();
    expect(member.experience).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.experience).toEqualTypeOf<number>();
    expect(member.level).toBeDefined();
    expect(member.level).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.level).toEqualTypeOf<number>();
    expect(member.hotm).toBeDefined();
    expect(member.hotm).toBeInstanceOf(HOTM);
    expectTypeOf(member.hotm).toEqualTypeOf<HOTM>();
    expect(member.highestMagicalPower).toBeDefined();
    expect(member.highestMagicalPower).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.highestMagicalPower).toEqualTypeOf<number>();
    expect(member.fairySouls).toBeDefined();
    expect(member.fairySouls).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairySouls).toEqualTypeOf<number>();
    expect(member.fairyExchanges).toBeDefined();
    expect(member.fairyExchanges).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.fairyExchanges).toEqualTypeOf<number>();
    expect(member.skills).toBeDefined();
    expect(member.skills).toBeInstanceOf(Skills);
    expectTypeOf(member.skills).toEqualTypeOf<Skills>();
    expect(member.bestiary).toBeDefined();
    expect(member.bestiary).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.bestiary).toEqualTypeOf<number>();
    expect(member.slayer).toBeDefined();
    expect(member.slayer).toBeInstanceOf(Slayers);
    expectTypeOf(member.slayer).toEqualTypeOf<Slayers>();
    expect(member.crimsonIsle).toBeDefined();
    expect(member.crimsonIsle).toBeInstanceOf(CrimsonIsle);
    expectTypeOf(member.crimsonIsle).toEqualTypeOf<CrimsonIsle>();
    expect(member.dungeons).toBeDefined();
    expect(member.dungeons).toBeInstanceOf(Dungeons);
    expectTypeOf(member.dungeons).toEqualTypeOf<Dungeons>();
    expect(member.collections).toBeDefined();
    expectTypeOf(member.collections).toEqualTypeOf<Record<string, number>>();
    expect(member.purse).toBeDefined();
    expect(member.purse).toBeGreaterThanOrEqual(0);
    expectTypeOf(member.purse).toEqualTypeOf<number>();
    expect(member.stats).toBeDefined();
    expect(member.stats).toBeInstanceOf(Stats);
    expectTypeOf(member.stats).toEqualTypeOf<Stats>();
    expect(member.pets).toBeDefined();
    expectTypeOf(member.pets).toEqualTypeOf<SkyblockPet[]>();
    member.pets.forEach((pet: SkyblockPet) => {
      expect(pet).toBeDefined();
      expect(pet).toBeInstanceOf(SkyblockPet);
      expectTypeOf(pet).toEqualTypeOf<SkyblockPet>();
      expect(pet.uuid).toBeDefined();
      expectTypeOf(pet.uuid).toEqualTypeOf<string>();
      expect(pet.name).toBeDefined();
      expectTypeOf(pet.name).toEqualTypeOf<string>();
      expect(pet.xp).toBeDefined();
      expect(pet.xp).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.xp).toEqualTypeOf<number>();
      expect(pet.active).toBeDefined();
      expectTypeOf(pet.active).toEqualTypeOf<boolean>();
      expect(pet.rarity).toBeDefined();
      expectTypeOf(pet.rarity).toEqualTypeOf<Rarity>();
      expect(pet.petScore).toBeDefined();
      expect(pet.petScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.petScore).toEqualTypeOf<number>();
      expect(pet.heldItem).toBeDefined();
      expectTypeOf(pet.heldItem).toEqualTypeOf<string | null>();
      expect(pet.candyUsed).toBeDefined();
      expect(pet.candyUsed).toBeGreaterThanOrEqual(0);
      expectTypeOf(pet.candyUsed).toEqualTypeOf<number>();
      expect(pet.skin).toBeDefined();
      expectTypeOf(pet.skin).toEqualTypeOf<string | null>();
    });
    expect(member.jacob).toBeDefined();
    expect(member.jacob).toBeInstanceOf(Jacob);
    expectTypeOf(member.jacob).toEqualTypeOf<Jacob>();
    expect(member.chocolate).toBeDefined();
    expect(member.chocolate).toBeInstanceOf(ChocolateFactory);
    expectTypeOf(member.chocolate).toEqualTypeOf<ChocolateFactory>();
    expect(member.minions).toBeDefined();
    expect(member.minions).toBeInstanceOf(Minions);
    expectTypeOf(member.minions).toEqualTypeOf<Minions>();
    expect(member.getArmor).toBeDefined();
    expectTypeOf(member.getArmor).toEqualTypeOf<() => Promise<Armor>>();
    const armor = await member.getArmor();
    expect(armor).toBeDefined();
    expectTypeOf(armor).toEqualTypeOf<Armor>();
    expect(armor.helmet).toBeDefined();
    expectTypeOf(armor.helmet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.chestplate).toBeDefined();
    expectTypeOf(armor.chestplate).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.leggings).toBeDefined();
    expectTypeOf(armor.leggings).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(armor.boots).toBeDefined();
    expectTypeOf(armor.boots).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getWardrobe).toBeDefined();
    expectTypeOf(member.getWardrobe).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const wardrobe = await member.getWardrobe();
    expect(wardrobe).toBeDefined();
    expectTypeOf(wardrobe).toEqualTypeOf<SkyblockInventoryItem[]>();
    wardrobe.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getEnderChest).toBeDefined();
    expectTypeOf(member.getEnderChest).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const enderChest = await member.getEnderChest();
    expect(enderChest).toBeDefined();
    expectTypeOf(enderChest).toEqualTypeOf<SkyblockInventoryItem[]>();
    enderChest.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getInventory).toBeDefined();
    expectTypeOf(member.getInventory).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const inventory = await member.getInventory();
    expect(inventory).toBeDefined();
    expectTypeOf(inventory).toEqualTypeOf<SkyblockInventoryItem[]>();
    inventory.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getPetScore).toBeDefined();
    expectTypeOf(member.getPetScore).toEqualTypeOf<() => number>();
    const petScore = member.getPetScore();
    expect(petScore).toBeDefined();
    expect(member.getEquipment).toBeDefined();
    expectTypeOf(member.getEquipment).toEqualTypeOf<() => Promise<Equipment>>();
    const equipment = await member.getEquipment();
    expect(equipment).toBeDefined();
    expectTypeOf(equipment).toEqualTypeOf<Equipment>();
    expect(equipment).toBeDefined();
    expectTypeOf(equipment).toEqualTypeOf<Equipment>();
    expect(equipment.gauntlet).toBeDefined();
    expectTypeOf(equipment.gauntlet).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.belt).toBeDefined();
    expectTypeOf(equipment.belt).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.cloak).toBeDefined();
    expectTypeOf(equipment.cloak).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(equipment.necklace).toBeDefined();
    expectTypeOf(equipment.necklace).toEqualTypeOf<SkyblockInventoryItem | null>();
    expect(member.getPersonalVault).toBeDefined();
    expectTypeOf(member.getPersonalVault).toEqualTypeOf<() => Promise<SkyblockInventoryItem[]>>();
    const vault = await member.getPersonalVault();
    expect(vault).toBeDefined();
    expectTypeOf(vault).toEqualTypeOf<SkyblockInventoryItem[]>();
    vault.forEach((item: SkyblockInventoryItem) => {
      expect(item).toBeDefined();
      expect(item).toBeInstanceOf(SkyblockInventoryItem);
      expectTypeOf(item).toEqualTypeOf<SkyblockInventoryItem>();
      expect(item.itemId).toBeDefined();
      expect(item.itemId).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.itemId).toEqualTypeOf<number>();
      expect(item.count).toBeDefined();
      expect(item.count).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.count).toEqualTypeOf<number>();
      expect(item.name).toBeDefined();
      expectTypeOf(item.name).toEqualTypeOf<string>();
      expect(item.lore).toBeDefined();
      expectTypeOf(item.lore).toEqualTypeOf<string>();
      expect(item.loreArray).toBeDefined();
      expectTypeOf(item.loreArray).toEqualTypeOf<string[]>();
      expect(item.loreForEmbed).toBeDefined();
      expectTypeOf(item.loreForEmbed).toEqualTypeOf<string>();
      expect(item.color).toBeDefined();
      expectTypeOf(item.color).toEqualTypeOf<string | null>();
      expect(item.enchantments).toBeDefined();
      expectTypeOf(item.enchantments).toEqualTypeOf<Record<string, number>>();
      expect(item.reforge).toBeDefined();
      expectTypeOf(item.reforge).toEqualTypeOf<string>();
      expect(item.gemstones).toBeDefined();
      expectTypeOf(item.gemstones).toEqualTypeOf<SkyblockGemstone[] | []>();
      expect(item.damage).toBeDefined();
      expect(item.damage).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.damage).toEqualTypeOf<number>();
      expect(item.rarity).toBeDefined();
      expectTypeOf(item.rarity).toEqualTypeOf<Rarity>();
      expect(item.dungeonStars).toBeDefined();
      expect(item.dungeonStars).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.dungeonStars).toEqualTypeOf<number>();
      expect(item.gearScore).toBeDefined();
      expect(item.gearScore).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.gearScore).toEqualTypeOf<number>();
      expect(item.uuid).toBeDefined();
      expectTypeOf(item.uuid).toEqualTypeOf<string>();
      expect(item.soulbound).toBeDefined();
      expectTypeOf(item.soulbound).toEqualTypeOf<boolean>();
      expect(item.artOfWar).toBeDefined();
      expect(item.artOfWar).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.artOfWar).toEqualTypeOf<number>();
      expect(item.rune).toBeDefined();
      expectTypeOf(item.rune).toEqualTypeOf<object>();
      expect(item.hotPotatoBooks).toBeDefined();
      expect(item.hotPotatoBooks).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hotPotatoBooks).toEqualTypeOf<number>();
      expect(item.recombobulated).toBeDefined();
      expectTypeOf(item.recombobulated).toEqualTypeOf<boolean>();
      expect(item.attributes).toBeDefined();
      expectTypeOf(item.attributes).toEqualTypeOf<object>();
      expect(item.hecatomb).toBeDefined();
      expect(item.hecatomb).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.hecatomb).toEqualTypeOf<number>();
      expect(item.champion).toBeDefined();
      expect(item.champion).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.champion).toEqualTypeOf<number>();
      expect(item.cultivating).toBeDefined();
      expect(item.cultivating).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.cultivating).toEqualTypeOf<number>();
      expect(item.expertise).toBeDefined();
      expect(item.expertise).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.expertise).toEqualTypeOf<number>();
      expect(item.compact).toBeDefined();
      expect(item.compact).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.compact).toEqualTypeOf<number>();
      expect(item.blocksWalked).toBeDefined();
      expect(item.blocksWalked).toBeGreaterThanOrEqual(0);
      expectTypeOf(item.blocksWalked).toEqualTypeOf<number>();
    });
    expect(member.getNetworth).toBeDefined();
    expectTypeOf(member.getNetworth).toEqualTypeOf<() => Promise<NetworthResult | null>>();
    const networth = await member.getNetworth();
    expect(networth).toBeDefined();
    expectTypeOf(networth).toEqualTypeOf<NetworthResult | null>();
    expect(member.getFarmingWeight).toBeDefined();
    expectTypeOf(member.getFarmingWeight).toEqualTypeOf<() => number>();
    const farmingWeight = member.getFarmingWeight();
    expect(farmingWeight).toBeDefined();
    expect(farmingWeight).toBeGreaterThanOrEqual(0);
    expectTypeOf(farmingWeight).toEqualTypeOf<number>();
  });
  client.destroy();
});
