import Achievements from './Achievements';
import Arcade from '../MiniGames/Arcade';
import ArenaBrawl from '../MiniGames/ArenaBrawl';
import BedWars from '../MiniGames/BedWars';
import BlitzSurvivalGames from '../MiniGames/BlitzSurvivalGames';
import BuildBattle from '../MiniGames/BuildBattle';
import Color from '../Color';
import CopsAndCrims from '../MiniGames/CopsAndCrims';
import Cosmetics from './Cosmetics';
import Duels from '../MiniGames/Duels';
import Gifting from './Gifting';
import Guild from '../Guild/Guild';
import House from '../House';
import Housing from '../Housing';
import MegaWalls from '../MiniGames/MegaWalls';
import MurderMystery from '../MiniGames/MurderMystery';
import Paintball from '../MiniGames/Paintball';
import Parkour from './Parkour';
import Pit from '../MiniGames/Pit';
import Player from './Player';
import Quakecraft from '../MiniGames/Quakecraft';
import Quests from './Quests';
import RecentGame from '../RecentGame';
import Rewards from './Rewards';
import Seasonal from './Seasonal';
import SkyWars from '../MiniGames/SkyWars';
import SmashHeroes from '../MiniGames/SmashHeroes';
import SocialMedia from './SocialMedia';
import SpeedUHC from '../MiniGames/SpeedUHC';
import TNTGames from '../MiniGames/TNTGames';
import Tourney from './Tourney';
import TurboKartRacers from '../MiniGames/TurboKartRacers';
import UHC from '../MiniGames/UHC';
import VampireZ from '../MiniGames/VampireZ';
import Walls from '../MiniGames/Walls';
import Warlords from '../MiniGames/Warlords';
import WoolGames from '../MiniGames/WoolGames';
import { ChatChannel, Language, LevelProgress, PlayerRank, PlayerStats, ScorpiusBribe } from './Types';
import { expect, expectTypeOf, test } from 'vitest';

test('Player', () => {
  const data = new Player({ stats: 'meow' }, { guild: null, houses: null, recentGames: null });
  expect(data).toBeDefined();
  expect(data).toBeInstanceOf(Player);
  expectTypeOf(data).toEqualTypeOf<Player>();
  expect(data.uuid).toBeDefined();
  expectTypeOf(data.uuid).toEqualTypeOf<string>();
  expect(data.nickname).toBeDefined();
  expectTypeOf(data.nickname).toEqualTypeOf<string>();
  expect(data.rank).toBeDefined();
  expectTypeOf(data.rank).toEqualTypeOf<PlayerRank>();
  expect(data.mvpPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusColor).toEqualTypeOf<Color | null>();
  expect(data.mvpPlusPlusColor).toBeDefined();
  expectTypeOf(data.mvpPlusPlusColor).toEqualTypeOf<Color | null>();
  expect(data.gifting).toBeDefined();
  expectTypeOf(data.gifting).toEqualTypeOf<Gifting>();
  expect(data.socialMedia).toBeDefined();
  expectTypeOf(data.socialMedia).toEqualTypeOf<SocialMedia[]>();
  expect(data.firstLoginTimestamp).toBeDefined();
  expect(data.firstLoginTimestamp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.firstLoginTimestamp).toEqualTypeOf<number>();
  expect(data.firstLoginAt).toBeDefined();
  expectTypeOf(data.firstLoginAt).toEqualTypeOf<Date>();
  expect(data.lastLoginTimestamp).toBeDefined();
  expectTypeOf(data.lastLoginTimestamp).toEqualTypeOf<number | null>();
  expect(data.lastLoginAt).toBeDefined();
  expectTypeOf(data.lastLoginAt).toEqualTypeOf<Date | null>();
  expect(data.achievements).toBeDefined();
  expectTypeOf(data.achievements).toEqualTypeOf<Achievements>();
  expect(data.language).toBeDefined();
  expectTypeOf(data.language).toEqualTypeOf<Language>();
  expect(data.channel).toBeDefined();
  expectTypeOf(data.channel).toEqualTypeOf<ChatChannel>();
  expect(data.exp).toBeDefined();
  expect(data.exp).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.exp).toEqualTypeOf<number>();
  expect(data.level).toBeDefined();
  expectTypeOf(data.level).toEqualTypeOf<LevelProgress>();
  expect(data.seasonal).toBeDefined();
  expectTypeOf(data.seasonal).toEqualTypeOf<Seasonal>();
  expect(data.karma).toBeDefined();
  expect(data.karma).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.karma).toEqualTypeOf<number>();
  expect(data.freeSkyblockCookie).toBeDefined();
  expectTypeOf(data.freeSkyblockCookie).toEqualTypeOf<number | null>();
  expect(data.tourney).toBeDefined();
  expectTypeOf(data.tourney).toEqualTypeOf<Tourney>();
  expect(data.rewards).toBeDefined();
  expectTypeOf(data.rewards).toEqualTypeOf<Rewards>();
  expect(data.challenges).toBeDefined();
  expectTypeOf(data.challenges).toEqualTypeOf<object>();
  expect(data.parkour).toBeDefined();
  expectTypeOf(data.parkour).toEqualTypeOf<Parkour[]>();
  expect(data.housing).toBeDefined();
  expectTypeOf(data.housing).toEqualTypeOf<Housing>();
  expect(data.cosmetics).toBeDefined();
  expectTypeOf(data.cosmetics).toEqualTypeOf<Cosmetics>();
  expect(data.scorpiusBribes).toBeDefined();
  expectTypeOf(data.scorpiusBribes).toEqualTypeOf<ScorpiusBribe[]>();
  expect(data.quests).toBeDefined();
  expectTypeOf(data.quests).toEqualTypeOf<Quests>();
  expect(data.guild).toBeDefined();
  expectTypeOf(data.guild).toEqualTypeOf<Guild | null>();
  expect(data.houses).toBeDefined();
  expectTypeOf(data.houses).toEqualTypeOf<House[] | null>();
  expect(data.recentGames).toBeDefined();
  expectTypeOf(data.recentGames).toEqualTypeOf<RecentGame[] | null>();
  expect(data.stats).toBeDefined();
  expectTypeOf(data.stats).toEqualTypeOf<PlayerStats>();
  expect(data.stats.arcade).toBeDefined();
  expect(data.stats.arcade).toBeInstanceOf(Arcade);
  expectTypeOf(data.stats.arcade).toEqualTypeOf<Arcade>();
  expect(data.stats.arena).toBeDefined();
  expect(data.stats.arena).toBeInstanceOf(ArenaBrawl);
  expectTypeOf(data.stats.arena).toEqualTypeOf<ArenaBrawl>();
  expect(data.stats.bedwars).toBeDefined();
  expect(data.stats.bedwars).toBeInstanceOf(BedWars);
  expectTypeOf(data.stats.bedwars).toEqualTypeOf<BedWars>();
  expect(data.stats.blitzsg).toBeDefined();
  expect(data.stats.blitzsg).toBeInstanceOf(BlitzSurvivalGames);
  expectTypeOf(data.stats.blitzsg).toEqualTypeOf<BlitzSurvivalGames>();
  expect(data.stats.buildbattle).toBeDefined();
  expect(data.stats.buildbattle).toBeInstanceOf(BuildBattle);
  expectTypeOf(data.stats.buildbattle).toEqualTypeOf<BuildBattle>();
  expect(data.stats.copsandcrims).toBeDefined();
  expect(data.stats.copsandcrims).toBeInstanceOf(CopsAndCrims);
  expectTypeOf(data.stats.copsandcrims).toEqualTypeOf<CopsAndCrims>();
  expect(data.stats.duels).toBeDefined();
  expect(data.stats.duels).toBeInstanceOf(Duels);
  expectTypeOf(data.stats.duels).toEqualTypeOf<Duels>();
  expect(data.stats.megawalls).toBeDefined();
  expect(data.stats.megawalls).toBeInstanceOf(MegaWalls);
  expectTypeOf(data.stats.megawalls).toEqualTypeOf<MegaWalls>();
  expect(data.stats.murdermystery).toBeDefined();
  expect(data.stats.murdermystery).toBeInstanceOf(MurderMystery);
  expectTypeOf(data.stats.murdermystery).toEqualTypeOf<MurderMystery>();
  expect(data.stats.paintball).toBeDefined();
  expect(data.stats.paintball).toBeInstanceOf(Paintball);
  expectTypeOf(data.stats.paintball).toEqualTypeOf<Paintball>();
  expect(data.stats.pit).toBeDefined();
  expect(data.stats.pit).toBeInstanceOf(Pit);
  expectTypeOf(data.stats.pit).toEqualTypeOf<Pit>();
  expect(data.stats.quakecraft).toBeDefined();
  expect(data.stats.quakecraft).toBeInstanceOf(Quakecraft);
  expectTypeOf(data.stats.quakecraft).toEqualTypeOf<Quakecraft>();
  expect(data.stats.skywars).toBeDefined();
  expect(data.stats.skywars).toBeInstanceOf(SkyWars);
  expectTypeOf(data.stats.skywars).toEqualTypeOf<SkyWars>();
  expect(data.stats.smashheroes).toBeDefined();
  expect(data.stats.smashheroes).toBeInstanceOf(SmashHeroes);
  expectTypeOf(data.stats.smashheroes).toEqualTypeOf<SmashHeroes>();
  expect(data.stats.speeduhc).toBeDefined();
  expect(data.stats.speeduhc).toBeInstanceOf(SpeedUHC);
  expectTypeOf(data.stats.speeduhc).toEqualTypeOf<SpeedUHC>();
  expect(data.stats.tntgames).toBeDefined();
  expect(data.stats.tntgames).toBeInstanceOf(TNTGames);
  expectTypeOf(data.stats.tntgames).toEqualTypeOf<TNTGames>();
  expect(data.stats.turbokartracers).toBeDefined();
  expect(data.stats.turbokartracers).toBeInstanceOf(TurboKartRacers);
  expectTypeOf(data.stats.turbokartracers).toEqualTypeOf<TurboKartRacers>();
  expect(data.stats.uhc).toBeDefined();
  expect(data.stats.uhc).toBeInstanceOf(UHC);
  expectTypeOf(data.stats.uhc).toEqualTypeOf<UHC>();
  expect(data.stats.vampirez).toBeDefined();
  expect(data.stats.vampirez).toBeInstanceOf(VampireZ);
  expectTypeOf(data.stats.vampirez).toEqualTypeOf<VampireZ>();
  expect(data.stats.walls).toBeDefined();
  expect(data.stats.walls).toBeInstanceOf(Walls);
  expectTypeOf(data.stats.walls).toEqualTypeOf<Walls>();
  expect(data.stats.warlords).toBeDefined();
  expect(data.stats.warlords).toBeInstanceOf(Warlords);
  expectTypeOf(data.stats.warlords).toEqualTypeOf<Warlords>();
  expect(data.stats.woolgames).toBeDefined();
  expect(data.stats.woolgames).toBeInstanceOf(WoolGames);
  expectTypeOf(data.stats.woolgames).toEqualTypeOf<WoolGames>();
});
