import CopsAndCrimsDefusal from './CopsAndCrimsDefusal.js';
import { expect, expectTypeOf, test } from 'vitest';

test('CopsAndCrimsDefusal', () => {
  const data = new CopsAndCrimsDefusal({ stats: 'meow' });
  expect(data).toBeInstanceOf(CopsAndCrimsDefusal);
  expectTypeOf(data).toEqualTypeOf<CopsAndCrimsDefusal>();
  expect(data.kills).toBeDefined();
  expect(data.kills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.kills).toEqualTypeOf<number>();
  expect(data.headshotKills).toBeDefined();
  expect(data.headshotKills).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.headshotKills).toEqualTypeOf<number>();
  expect(data.assists).toBeDefined();
  expect(data.assists).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.assists).toEqualTypeOf<number>();
  expect(data.deaths).toBeDefined();
  expect(data.deaths).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.deaths).toEqualTypeOf<number>();
  expect(data.KDR).toBeDefined();
  expect(data.KDR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.KDR).toEqualTypeOf<number>();
  expect(data.wins).toBeDefined();
  expect(data.wins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.wins).toEqualTypeOf<number>();
  expect(data.gamesPlayed).toBeDefined();
  expect(data.gamesPlayed).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.gamesPlayed).toEqualTypeOf<number>();
  expect(data.losses).toBeDefined();
  expect(data.losses).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.losses).toEqualTypeOf<number>();
  expect(data.WLR).toBeDefined();
  expect(data.WLR).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.WLR).toEqualTypeOf<number>();
  expect(data.roundWins).toBeDefined();
  expect(data.roundWins).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.roundWins).toEqualTypeOf<number>();
  expect(data.shotsFired).toBeDefined();
  expect(data.shotsFired).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.shotsFired).toEqualTypeOf<number>();
  expect(data.bombsDefused).toBeDefined();
  expect(data.bombsDefused).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bombsDefused).toEqualTypeOf<number>();
  expect(data.bombsPlanted).toBeDefined();
  expect(data.bombsPlanted).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.bombsPlanted).toEqualTypeOf<number>();
  expect(data.killsAsCrim).toBeDefined();
  expect(data.killsAsCrim).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsAsCrim).toEqualTypeOf<number>();
  expect(data.killsAsCop).toBeDefined();
  expect(data.killsAsCop).toBeGreaterThanOrEqual(0);
  expectTypeOf(data.killsAsCop).toEqualTypeOf<number>();
});
